### ISSUE TITLE
Compiler warning during build in XCode 6.1 6A2008a

### ISSUE THREAD

**Issue by albertbori** [tcurdt/TCMobileProvision#1]
Doesn't appear to be anything serious. Only a minor nuisance, as I have to look at the warning every time I compile:

> /Users/me/dev/myapp/Pods/TCMobileProvision/Sources/iOS/TCMobileProvision.m:59:34: 'propertyListFromData:mutabilityOption:format:errorDescription:' is deprecated: first deprecated in iOS 8.0 - Use propertyListWithData:options:format:error: instead.

**Comment by tcurdt** [comment]
Thanks for reporting!
